### ISSUE TITLE
Inequality constraints

### ISSUE THREAD

**Issue by goghino** [goghino/SCOPFopt#1]
Hi Samuel, this is not correct. Assume x = [100, -1 , -1, -1]. Your inequality constraint sum(x) >= 4 is satisfied, but the original constraints x(i) >=1 are not. The same applies to the upper bounds.

https://github.com/goghino/SCOPFopt/blob/e2588ff540a5ec0d39020af3bf4dd8080b19d290/cruzas_code/optizelle/examplehs071_optizelle.m#L79

**Comment by cruzas** [comment]
Hi Juraj, 
Thanks! I think I've fixed the problem regarding the constraints.
