### ISSUE TITLE
Hessian

### ISSUE THREAD

**Issue by goghino** [goghino/SCOPFopt#2]
Try to express H as a single matrix, i.e. 
```
H = [ 2*x(4), x(4), x(4), 2*x(1) + x(2) + x(3); ...
x(4),  0,  0, x(1); ...
etc. ]
```

> can we simply change this to ... H_dx = H*dx ?

Yes, this is not HPC class, you don't have to write your own BLAS routines :)

https://github.com/goghino/SCOPFopt/blob/e2588ff540a5ec0d39020af3bf4dd8080b19d290/cruzas_code/optizelle/examplehs071_optizelle.m#L23

**Comment by cruzas** [comment]
All right, thanks a lot!
