### ISSUE TITLE
Jacobian

### ISSUE THREAD

**Issue by goghino** [goghino/SCOPFopt#3]
See my note to the Hessian assembly, express it as J = [...]. I think it it easier to read than scanning multiple lines, reading indexes and visualizing the matrix in one's own mind.

https://github.com/goghino/SCOPFopt/blob/e2588ff540a5ec0d39020af3bf4dd8080b19d290/cruzas_code/optizelle/examplehs071_optizelle.m#L104

**Comment by cruzas** [comment]
Done :)
